### ISSUE TITLE
react-native run-android results in error - does not exist in the Haste module map

### ISSUE THREAD

**Issue by jcavell** [transistorsoft/rn-background-geolocation-demo#82]
Hi

I get this error after clone the latest demo app version.
I'm using OSX, `node 10.16.0`, `npm 6.9.0`  (also tried with `node 12.7.0`, `npm 6.10.0`; made no difference). Also ran `npm audit-fix`. Using `Java 8` (also tried `Java 11`).

I’m able to successfully run `npm install`, but when I run `react-native run-android` I get this error:

`error: bundling failed: Error: Unable to resolve module react-native-background-geolocation from /Users/xx/IdeaProjects/rn-background-geolocation-demo/src/react-native-background-geolocation.ts: Module react-native-background-geolocation does not exist in the Haste module map`

**Comment by christocracy** [comment]
Terminate your dev server and try again.

**Comment by jcavell** [comment]
I'm not sure what you mean by dev server. Do you mean the background-geolocation-console or something else?

In the logs I'm getting `::ffff:127.0.0.1 - - [30/Jul/2019:14:48:32 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500`

**Comment by christocracy** [comment]
Your react-native dev server.

**Comment by jcavell** [comment]
Do you mean metro (sorry I'm new to React Native)? I have restarted this and get the same result.

**Comment by christocracy** [comment]
I pushed an error to [package.json](https://github.com/transistorsoft/rn-background-geolocation-demo/commit/ee8fde770c6cdc274006331f441fff75f4bf0340), loading the plugin from local file-system rather than npm.

Re-clone the repo and try agin.

**Comment by jcavell** [comment]
I've pulled, done an npm install but still get the same error running react-native run-android

**Comment by christocracy** [comment]
```
$ rm -rf node_modules
$ rm package-lock.json
$ npm install
```

**Comment by jcavell** [comment]
Yep, `rm package-lock.json` did it, thanks!

**Comment by tamereltonsy** [comment]
same issue and solved by  rm package-lock.json  ... thanks alot
